### ISSUE TITLE
Python 3.4 run pdf2txt.py ImportError: No Module named 'six'

### ISSUE THREAD

**Issue by evaykl** [goulu/pdfminer#30]
updated python from 2.7 to 3.4 on my laptop (Windows)

test run command-line command  pdf2txt.py simple1.pdf 

return ImportError: no module named 'six'

I guess there's something wrong with the third line: import six

anyone knows how to fix it?

**Comment by goulu** [comment]
I guess you should reinstall packages after upgrading from 2.7 to 3.4.

setup.px contains line
     install_requires=['six', 'chardet'] if sys.version_info >= (3, 0) else ['six'],

so for Python 3.x it will also install package chardet, which is probably missing .

**Comment by goulu** [comment]
(assuming the answer was correct...)
